---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:30"
    groups:
      patches-and-minor-upgrades:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:30"
    groups:
      patches-and-minor-upgrades:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:30"
    groups:
      patches-and-minor-upgrades:
        update-types:
          - "minor"
          - "patch"
